### ISSUE TITLE
Add # as default comment for conf files

### ISSUE THREAD

**Issue by anntzer** [scrooloose/nerdcommenter#197]
Currently, nerdcommenter defaults to `/**/` for unknown filetypes.  I would suggest switching the default to `#...`, or at least for conf files, where this syntax seems much more common imo.

**Comment by alerque** [comment]
The default already is to use `#` delimiters for conf files. The problem you are likely hitting is that no file type is being set by vim. Next time try `:set ft=conf`. That should load a generic conf file syntax and NERDCommenter will do the right thing. The problem here is vim's file type detection, not this plugin. Given that C-style comments are by far the most common across unknown file types it seems reasonable to keep that as the default. Perhaps you can force vim to set that file type for all `*.conf` extensions rather than relying on its file type detection mechanism which catches conf files of known programs, but not necessarily all of them.
