### ISSUE TITLE
Script tags in HTML documents use HTML comments

### ISSUE THREAD

**Issue by chadfurman** [scrooloose/nerdcommenter#225]
This is a repeat of https://github.com/scrooloose/nerdcommenter/issues/17 which was marked as closed but never resolved.

**Comment by ob7** [comment]
Same with HTML code inside a PHP file.

**Comment by alerque** [comment]
I'd love to see a PR for this. I'm not maintaining this project and would love to see the feature myself, but am unlikely to have the time to implement it myself. If anybody comes up with a working contribution I'd be happy to consider it!

**Comment by jbaum012** [comment]
[Here's a function that has been working for me for PHP files with HTML and javascript comments](https://gist.github.com/jbaum012/e7c87721fe7756fdc718a12b46246827#file-nerdcommenter_php-vim)

**Comment by alerque** [comment]
@jbaum012 That's great. I might be interested in adding a few example hooks to the repository or even working out default ones per language so that people can enable this out of the box without scrounging around for hook scripts. Would you be interested in contributing this toward that?

**Comment by jbaum012** [comment]
@alerque By all means use the gist as an example if you'd like, but to be honest it's pretty hackish.  For example, syntax is actually set to java instead of javascript inside of `<script>` tags, and there are also some issues I ran into while trying to comment out the very first line in a php file.  What I'm trying to say is, there is definitely room for improvement.

**Comment by alerque** [comment]
I'm closing this issue in favor of #17 which was an older duplicate. We were collecting some other duplicate issues and I'm cleaning up. Using the oldest report as canonical seems like the most transparent arrangement.
