### ISSUE TITLE
Toggle Comment

### ISSUE THREAD

**Issue by ChinLeung** [scrooloose/nerdcommenter#252]
The toggle comment is not working: 

**[count]<leader>c<space> |NERDComToggleComment|** 

It's giving me the following error:

**E492: Not an editor command: NERDComToggleComment**

**Comment by alerque** [comment]
What binding are you using to call this function?

**Comment by ChinLeung** [comment]
I'm using this in my .vimrc:

**map <leader>c :NERDComToggleComment<cr>**

And whenever I try it, I get the not an editor command error.

**Comment by linde12** [comment]
I've got the same problem. Also `:help nerdcommenter` doesn't work, it just tells me "Sorry, no help for nerdcommenter"

**Comment by alerque** [comment]
@ChinLeung that just isn't even the correct syntax for setting up mappings to those kind of functions. You need either link into the plugin list using `<Plug>` or use a function caller like `:call`. This isn't an issue with this plugin, it's just the way plugins work. Additionally you need to pass the right modes and actions into the function or it won't know what you are doing even when you do call it.

Did you get the plugin working with the original bindings first? Do you know what your `<leader>` is? Once you get it working with the original bindings, then look into adding your own. You could use something like `:map c <Plug>NERDCommenterToggle('n', 'Toggle')<Cr>`. That being said if you don't like the bindings I highly recommend changing your leader, learning the original mappings, or if you really need to adjust the internal mapping table rather than manually mapping to the functions. You will run into timing issues mapping to just `c`. Also you should look into when to use the `:Xnoremap` variants instead of just `:map`.

@linde12 You haven't completely installed the plugin. You seem to have the plugin file but the built int documentation is in a separate text file that also needs to be placed where vim can find it. If you follow the installation instructions or use a plugin manage it should take care of that issue.

**Comment by linde12** [comment]
@alerque: Thanks, i just installed via Plug but i got used to the default keybinds so now i'm fine.
