### ISSUE TITLE
I wan't align all  = .= =. := =: for bitbake grammar, how to do it?

### ISSUE THREAD

**Issue by zzs213** [scrooloose/nerdcommenter#259]
For example:

For example from:

```
PATH        =.   '${common_path}:${tool_path}:'
PATH  .=   '${common_path}:${tool_path}:'
BOARD_DEBUG_ETHADDR     =  "02:80:AD:20:31:B8"
BOARD_DEF_IPADDR  = "192.168.0.13"
SERVER_HOST_IPADDR= "192.168.0.12"
DEFAULT_GATEWAY= "192.168.0.1"

yy := "dskj"
kk =: "dskf"
```

To:
```
PATH                 =. '${common_path}:${tool_path}:'
PATH                .=  '${common_path}:${tool_path}:'
BOARD_DEBUG_ETHADDR  =  "02:80:AD:20:31:B8"
BOARD_DEF_IPADDR     =  "192.168.0.13"
SERVER_HOST_IPADDR   =  "192.168.0.12"
DEFAULT_GATEWAY      =  "192.168.0.1"

yy                  :=  "dskj"
kk                   =: "dskf"
```

**Comment by alerque** [comment]
This does not seem like an issue with NerdCommenter. These are not comments, they are part of the language syntax. Since they are not comments NerdCommenter has no business handling them and is not made to do things like that.

If you have a question about how to accomplish something in any editor in the `vi` family I suggest you ask on the [Stack Exchange VI site](http://vi.stackexchange.com/).
