### ISSUE TITLE
Dose nerdcommenter provide a function that can judge where the current line is a comment?

### ISSUE THREAD

**Issue by woshichuanqilz** [scrooloose/nerdcommenter#262]
I want to write a function that do sth when the current line is a comment line for all type of files. 
So I wonder if there is a function or api sth can help me judge it

**Comment by alerque** [comment]
The `IsCommentedNormOrSexy(lineNum)` function should do the trick for you, but it is declared in the script scope rather than being global so you'll need to [figure out](http://stackoverflow.com/a/24027507/313192) how to get the script number to connect to the right namespace. What this does and how you can use it can be seen by example in the source code. Try looking at line 1776 for starters.

If you have any further questions about how to implement something in Vim I suggest you ask on the [Vi and Vim Stack Exchange site](https://vi.stackexchange.com/) as this issue tracker is not the best place for this sort of question.
