### ISSUE TITLE
Basic usage issues

### ISSUE THREAD

**Issue by andrey-gvrd** [scrooloose/nerdcommenter#263]
The tutorial gives this example:

    <leader>c$ |NERDComEOLComment|
    Comments the current line from the cursor to the end of line. 

But pressing `\c$` or `,c$` in vim copies the current line and switched to insert mode.

`:echo mapleader` doesn't output anything; I haven't added anything related to nerdcommenter to my `.vimrc`. `:map <leader>c$` outputs `n <Space>c$ <Plug>NERDCommenterToEOL`

**Comment by alerque** [comment]
Judging from the way the mapping expands for you, your existing vim configuration is screwed up and your leader key is <kbd>SPACE</kbd> rather than the usual <kbd>/</kbd> or sometimes alternative <kbd>,</kbd>. You should probably poke through your config and figure out where this is getting set and remove it, but it  can also  be set with something like this:

```vim
let mapleader = "\"
```

That being said if you leader is really <kbd>SPACE</kbd> as shown, then the function you are expecting _should_ work by pressing `<Space>c$`.

**Comment by alerque** [comment]
I found your vimrc in your Github profile, and you are remapping leader to space on [line 9](https://github.com/andrey-gvrd/vim-config/blob/master/vimrc#L9). That's your problem. The binding is going to start with a space for you. This is pretty unconventional and is likely to get you in a lot of trouble with other mappings, I highly recommend using a different leader.

**Comment by andrey-gvrd** [comment]
Wow, thanks for the expansive answer!

**Comment by TamaMcGlinn** [comment]
I should mention that using mapleader in a plugin without asking is pretty unconventional and is likely to break people's config.

**Comment by alerque** [comment]
@TamaMcGlinn *Using* the leader key is not unconventional at all, in fact it is quite common. This plugin will work just fine with SpaceVIM. The only issue here was a user expected it to work as if `\` was hard coded and when people talked about their bindings they expected theirs to work the same way when they had a different leader set. We use whatever the user has set which is *defacto* the way leader bindings are supposed to work.
