### ISSUE TITLE
Prevent defaults bindings

### ISSUE THREAD

**Issue by pytnik89** [scrooloose/nerdcommenter#267]
'map ,cc <plug>NERDCommenterToggle'
this command cant remap standard 'NERDCommenterComment', i would better use Toggle on this key combination, but can't do it.

**Comment by fcying** [comment]
I hava the same problem.

**Comment by fcying** [comment]
my vimrc:
```vim    
    let g:NERDCustomDelimiters = {
                \ 'c': { 'leftAlt': '/*', 'rightAlt': '*/', 'left': '//' },
                \ 'cpp': { 'leftAlt': '/*', 'rightAlt': '*/', 'left': '//' }
                \ }
    nmap <A-/> <plug>NERDCommenterToggle
    vmap <A-/> <plug>NERDCommenterToggle gv
    nmap <leader>cc <plug>NERDCommenterToggle
    vmap <leader>cc <plug>NERDCommenterToggle gv
```
```vim  
the <A-/> map work ok, but the <leader>cc not remap, when I type :map, I can see 
n ,cc <plug>NERDCommenterComment, not remap to NERDCommenterToggle
```

**Comment by alerque** [comment]
@fcying Copy and paste from your post to the vim command prompt `:nmap <leader>cc <plug>NERDCommenterToggle` I can use my leader and the binding as <kbd>\<kbd><kbd>c</kbd><kbd>c</kbd> to toggle comments. Where and how are you changing your leader from the default?

**Comment by fcying** [comment]
I change default leader at top of my vimrc.
I try set map in vim command, it will work ok, but set map in vimrc work no correctly.
I add autocmd to set map after vimenter in vimrc, it can wok now.

```vim
    autocmd! VimEnter * call s:fcy_nerdcommenter_map()
    function! s:fcy_nerdcommenter_map()
        nmap <leader>cc <plug>NERDCommenterToggle
        vmap <leader>cc <plug>NERDCommenterToggle gv
    endfunction
```

**Comment by alerque** [comment]
Okay this is a function of the plugin getting loaded for some file types after your rc is processed, thus overwriting your manually changed mappings. This is not an issue if you want to create _new_ bindings but is an issue if you want to re-use the _existing_ ones.

You can prevent the default bindings from being created by setting a flag in your rc:

```vim
let g:NERDCreateDefaultMappings = 0
```

The catch is that then you are responsible for setting up ALL your own bindings because you don't get any of the default ones. The price of playing with fire ;-)
