### ISSUE TITLE
beep after <leader>c, <leader>w it's work

### ISSUE THREAD

**Issue by hybridsong** [scrooloose/nerdcommenter#282]
Ubuntu Server 16.04.1 LTS / VIM - Vi IMproved 7.4

At first I thought this is keyboard shortcut problem, but I also try other plugin eg. easymotion, it's work.

**Comment by alerque** [comment]
I'm afraid I don't really understand what your problem is. Can you describe more fully what you are doing, what the expected result is and what actually happens?

Also if you can include the output of `:map <leader>c` from the vim command  prompt to show what your current bindings starting with <kbd>Leader</kbd><kbd>C</kbd> are that would be helpful.

**Comment by hybridsong** [comment]
Your suggestion is helpful, I have resolved the problem!

**Comment by alerque** [comment]
I take it there isn't an actual issue with this plugin then, correct?
