### ISSUE TITLE
How  can I change the default commentstring for `no filetype` document?

### ISSUE THREAD

**Issue by zhenguoli** [scrooloose/nerdcommenter#285]
I want to comment a text file, but the filetype is `none`. And I type `<Leader>cc` command on that line.   
For example:  
'hello world'    
then it will become    
'/* hello world */' 
    
Then I check the value of `commentstring`, which is `commentstring=/*%s*/`.   
But I want to change the commented text 'hello world' to **`// hello world`**. I have set `commentstring=// %s` but there is no effect on that line, it still comment it as '/* hello world */'.    
So, how can I change the default commentstring to comment the text to '// hello world'.  
Thanks!

**Comment by lizhenguo** [comment]
I have found the method to inspect and set the correct value.

**Comment by alerque** [comment]
Great @lizhenguo, glad you found it. Would you mind noting what method you used for future reference of other people searching that may find this issue?

**Comment by lizhenguo** [comment]
Yes. Thanks.
First you can check where the option `commentstring` was last changed by `verbose set commentstring?`. Then it just return `commentstring=/*%s*/`.  
And because `verbose` tells Vim to show where the option was last changed, so the fact that it doesn't report where it was last changed suggests that it's the global default.  
So as far as I'm concerned, I set the `commentstring` in `~/.vimrc` by `set commentstring=//\ %s`.
Here, you should note how to include white space in a string option value.
In Vim help files(options.txt):
>To include white space in a string option value it has to be preceded with a
backslash. 

So, Vim 'string constant' is different from 'string option value'. If you adapt `set commentstring="// %s"`, the option setting will not work as you expected, because you set the 'string option value' as the 'string constant'. This is the problem I have encountered in how to solve the problem.

**Comment by alerque** [comment]
It seems like there should be an easier way to do this. I thought I know one, but apparently not. I'm going to re-open this so we get a better fix either implemented or documented.

**Comment by lizhenguo** [comment]
Yes, finding an easier way to do this is better. I hope we can get a good way.

**Comment by goyatparmod** [comment]
Did you guys find out the solution for this.?

**Comment by lizhenguo** [comment]
@goyatparmod , I set the commentstring in `~/.vimrc` by `set commentstring=//\ %s`.

**Comment by lizhenguo** [comment]
I set the commentstring in ~/.vimrc by: 
set commentstring=//\ %s

Note how to include white space in a string option value. To include whitespace in a string option value it has to be preceded with a
backslash.2017-06-15 12:44:35>"Parmod Kumar" wrote:

Did you guys find out the solution for this.?

**Comment by mohd-akram** [comment]
Any update on this? In the meantime, could the default be changed to `#` as it is more prevalent for configuration files and shell scripts, both of which are often extensionless.

**Comment by sentientmachine** [comment]
There's a way to set the default in the plugin rather than in the `.vimrc`.  I made the change in my `NERD_commenter.vim`, so that it is proactive to set a default commentstring for no filetype, rather than having to fall back and rely on vim's default global settings defined in /etc/vimrc or `.vimrc` as explained before. 

1.  Find and open `NERD_commenter.vim`
2.  Inside there find the method named `CreateDelimMapFromCms()`
3.  Do a search for the builtin variable `&commentstring`
4.  This is where nerdcommenter is sucking in the global vim settings.
5.  You see these lines:
```
     "    \ 'left': substitute(&commentstring, '\([^ \t]*\)\s*%s.*', '\1', ''), 
     "    \ 'right': substitute(&commentstring, '.*%s\s*\(.*\)', '\1', 'g'), 
     "    \ 'nested': 0, 
     "    \ 'leftAlt': '', 
     "    \ 'rightAlt': '', 
     "    \ 'nestedAlt': 0
```} 
6.  Change those lines to this:
```
     "    \ 'left': '# ', 
     "    \ 'right': '', 
     "    \ 'nested': 0, 
     "    \ 'leftAlt': '', 
     "    \ 'rightAlt': '', 
     "    \ 'nestedAlt': 0
```} 
  
Now test to see if it worked:

1.  Open any file.
2.  Run `set ft=`
3.  Select text and press command to comment lines.
4.  The default comment char is # as specified above.

**Comment by alerque** [comment]
@sentientmachine I'm glad you found something useful for yourself, but allow me to explain why we won't be making that the plugin default.

* Falling back on VIM's values actually covers more use cases. Maybe it doesn't do what you want, but out of the box it will support more scenarios correctly.

* Your solution will require you to use your own fork of this plugin and keep it updated upstream. That requires moving files or configs around with you. This is what `vimrc` was designed for. You take your dotfiles with you to set your user preferences allowing you to use things like this plugin out of the box (including staying up to date) without having to do manual customization work.

I highly recommend just setting vim's default commentstring variable in your rc file as the most portable and least brittle solution.
