### ISSUE TITLE
"Default delimiter customisation" doesn't work.

### ISSUE THREAD

**Issue by zhou13** [scrooloose/nerdcommenter#33]
According to document, 
add
    let NERD_cpp_alt_style=1
    let NERD_c_alt_style=1
to vimrc should switching commenting style. But it doesn't. And I doesn't see any related code in the script.

**Comment by alerque** [comment]
I've recently been added as a maintainer on this project and am working through the issue backlog. It does look like this feature was never implemented and only the documentation exists. I don't have time to do a bunch of dev work on this—I'm mostly just coordinating all the contributions—but if somebody would like to actually set this up I'd be glad to review a PR that fixes this. Otherwise the thing to do might be to delete the bogus documentation. Anybody?

**Comment by alerque** [comment]
See PR #155 for a (partial?) implementation of this.

**Comment by alerque** [comment]
With many thanks to @saep for actually implementing this, I have merged the PR that adds this feature and made a few tweaks. Please note that I changed the actual preference key format to be more like the other values. For example to always default to the alternates for java:

```vim
let g:NERDAltDelims_java = 1
```

Note this is documented in help and now in the README as well. Let be know if anybody has trouble with the feature.
