### ISSUE TITLE
Toggle Broken for React JSX

### ISSUE THREAD

**Issue by redreceipt** [scrooloose/nerdcommenter#345]
Trying to comment JSX tries to use inline Javascript comments:
`//<header>`

![2018-09-25 16 59 02](https://user-images.githubusercontent.com/2659478/46042858-73a3ef00-c0e4-11e8-9bf5-0f3184a23ee7.gif)

It needs to use block Javascript comments wrapped in curly braces when Vim senses JSX:
`{/*<header>*/}`

**Comment by mblarsen** [comment]
See #17

**Comment by alerque** [comment]
As I understand it the issue here is not this plugin, the issue is higher up in the food chain. Vim does not, as you suggest, "sense JSX". As far as Vim knows it _is_ working with a regular Javascript file. If I'm wrong there and there is a file type and detection available for JSX then we can fix this pretty easily, but if not you'll have to work around this by setting the desired mode and delimiter yourself when working with JSX files. There would be a lot of places you can do this including mode lines or local RC files or just some manual file type setting.

**Comment by redreceipt** [comment]
@alerque pretty sure it can. It's listed as `javascript.jsx` in my status line.

![screen shot 2018-12-11 at 4 47 44 pm](https://user-images.githubusercontent.com/2659478/49832418-96998300-fd64-11e8-97ea-ac27e3399d5c.png)

**Comment by alerque** [comment]
For those using Vim to program in React please see PR #393 and comments on our support for these filetypes in 41d31b3.
