### ISSUE TITLE
GitHub README has literally no indication of what this plugin does. 

### ISSUE THREAD

**Issue by masukomi** [scrooloose/nerdcommenter#388]
I have a desire related to commenting my code. Does this plugin address it? 

Who can say.

Does it let me comment on code? 

Is this somehow dependent on NERDTree? 

What does "Comments the given lines using only one set of multipart delimiters." mean? Does it comment out lines of code? does it make comments about the lines of code? 

Who can say.... It's a mystery.

**Comment by alerque** [comment]
I'm sorry, but even if there may be ambiguity in the README, this issue overstates your case. Why would it depend on a plugin that provides unrelated function and is _not mentioned anywhere_ just because it happens to share a generic English word in the name? Since I've never heard of any editor or plugin anywhere on any platform that uses the term "comment" is any sense other that of code comment syntax I don't think any clarification about not meaning "comments about lines of code" is necessary. 

The README has documentation in the usage section for [each function this plugin provides](https://github.com/scrooloose/nerdcommenter#default-mappings).

It's not a mystery. The readme can say (and already does).

**Comment by masukomi** [comment]
You may not agree about my wondering if NERDTree is related/require and i can certainly see your side of "comment about lines of code". However, I would respectfully request that you reconsider what the README actually says about the what the plugin does.  "Comment functions so powerful—no comment necessary." This doesn't actually tell a prospective user what this is for. There are many plugins in editors that allow you to leave comments not just comment out or uncomment code.  Without reading the nitty gritty "how to configure"  details a potential user can't know what this plugin does.

**Comment by alerque** [comment]
Feel free to contribute. No that's not sarcastic, I'm sure there is lots of room for improvement. I stepped in a while back to help maintain this plugin when PRs were years behind being merged and bugs that had fixes weren't getting into the plugin. I'm quite open to reviewing and accepting contributions, including to the documentation. But I don't have time to rewrite the readme. Feel free to have a go at it.
