### ISSUE TITLE
bug: remove comments pascal

### ISSUE THREAD

**Issue by andersoncustodio** [scrooloose/nerdcommenter#45]
Se tenho um bloco de código.

```
linha 1
linha 2
```

Use the command ",cs" visual block mode.

```
(* linha 1
 * linha 2
 *)
```

When I use "c <space>" does not remove it, instead creating another comment.

```
(* linha 1
 {* linha 2}
 *)
```

Sorry for the poorly written text, I do not know English.

**Comment by alerque** [comment]
This has to do with what delimiters you have setup as the primary vs. the alternate. The comment block you are showing is commented using the alternate delimiters + the sexy style. The command you are issuing is setup to look for the primary delimiters, which don't exist, so it adds a comment instead of removing.

You can swap the primary/alternate delimiters using `<leader>ca`, then your uncomment command should work on that block as you would expect.
